### ISSUE TITLE
can not install this three plugin for example  :  'Valloric/YouCompleteMe 

### ISSUE THREAD

**Issue by nmww** [ets-labs/vimrc#35]
![default](https://user-images.githubusercontent.com/6917516/41598831-fd6b5b52-7403-11e8-9bd1-c2d7bdb02488.png)
```Plugin 'Valloric/YouCompleteMe'       |~                                      
  Plugin 'klen/python-mode'             |~                                      
  Plugin 'scrooloose/syntastic'`

can not install this three plugin
for example  :  'Valloric/YouCompleteMe

**Comment by rmk135** [comment]
Hi @nmww ,

What kind of error do you get? Can you, please, make `:messages` and post its output?

**Comment by wj-Mcat** [comment]
@rmk135 I install by the setup.py file, it occurs error:

```text
Traceback (most recent call last):
  File "<string>", line 27, in <module>
  File "/home/users/wujingjing/.vim/bundle/YouCompleteMe/python/ycm/base.py", line 18, in <module>
    from ycm import vimsupport
  File "/home/users/wujingjing/.vim/bundle/YouCompleteMe/python/ycm/vimsupport.py", line 184
    f"bufnr('{ EscapeForVim( os.path.realpath( filename ) ) }', "
                                                                ^
SyntaxError: invalid syntax
```

**Comment by cydanil** [comment]
It seems that your vim uses Python2 instead of the expected Python3.  

Here's a post on an issue with more details:
https://github.com/ets-labs/python-vimrc/issues/39#issuecomment-607429122
